# https://taskfile.dev

version: '3'

tasks:
  default:
    deps: [py]
    #silent: true

  run:
    cmd:
      task: py

  py:
    desc: "Run via Python"
    cmd: uv run src/myapp/main.py
    sources:
      - src/myapp/
    method: timestamp

  debug:
    cmd: uv run python -i src/myapp/main.py
    sources:
      - src/myapp/
    method: checksum

  qt:
    desc: "View QML Scene"
    cmd: qml6 -I src/myapp/qml src/myapp/qml/Main.qml
    sources:
      - src/myapp/qml/**/*.qml
    #method: none
    method: timestamp
    #method: checksum
