name: qmllintbot
run-name: Linting qml code of PR
on:
  workflow_run:
    workflows: [push-build-release]
    types:
      - completed
jobs:
  download-comment:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.conclusion == 'success' }}
    
    permissions:
      actions: read
      pull-requests: write
      
    steps:
      - name: 'Download artifact'
        uses: actions/download-artifact@v4
        with:
          name: qmllint
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}

      - name: Read pr number
        id: getprn
        run: |
          cat pr_number
          echo "prn=$(cat pr_number)" >> $GITHUB_OUTPUT

      - name: 'Run QML Reviewer'
        uses: EddyTheCo/qmllint-action/@v0.1.0
        with:
          jsondir:  ${{ github.workspace }}
          pr_number: ${{ steps.getprn.outputs.prn }}
